# Exercise 5.02: Retrieving the Center Points and the Labels

In this exercise, you will be able to understand the usage of `cluster_centers_` and `labels_`.

The following steps will help you complete the exercise:

1.- Create the same 12 data points from Exercise 5.01,  but here, perform k-means clustering with four clusters, then show the cluster centers using the `.cluster_centers_` attribute.

Output:

```
array([[ 7.625     ,  0.75      ],
       [ 1.375     ,  9.5       ],
       [ 1.33333333,  1.5       ],
       [10.        , 10.        ]])
```

In [2]:
import numpy as np
import matplotlib.pyplot as plot
from sklearn.cluster import KMeans

data_points = np.array([
    [1, 1], 
    [1, 1.5],
    [2, 2],
    [8, 1],
    [8, 0],
    [8.5, 1],
    [6, 1],
    [1, 10],
    [1.5, 10],
    [1.5, 9.5],
    [10, 10],
    [1.5, 8.5]
])

k_means_model = KMeans(n_clusters=4,random_state=8)
k_means_model.fit(data_points)

centers = k_means_model.cluster_centers_
centers

array([[ 7.625     ,  0.75      ],
       [ 1.375     ,  9.5       ],
       [ 1.33333333,  1.5       ],
       [10.        , 10.        ]])

The output of the `cluster_centers_` property shows the x and y coordinates of the center points.

From the output, we can see the 4 centers, which are bottom right $(7.6, 0.75)$, top left $(1.3, 9.5)$, bottom left $(1.3, 1.5)$, and top right $(10, 10)$. We can also note that the fourth cluster (the top-right cluster) is only made of a single data point. This data point can be assumed to be an **outlier**.

2.- Get the labels using `.labels_`:

Output

```
array([2, 2, 2, 0, 0, 0, 0, 1, 1, 1, 3, 1], dtype=int32)
```

In [3]:
labels = k_means_model.labels_
labels

array([2, 2, 2, 0, 0, 0, 0, 1, 1, 1, 3, 1], dtype=int32)

The `labels_` property is an array of length 12, showing the cluster of each of the 12 data points it belongs to. The first cluster is associated with the number 0, the second is associated with 1, the third is associated with 2, and so on (remember that Python indexes always start from 0 and not 1).